name: Notify Team on Pull Request Reviewer Assignment
'on':
  pull_request:
    types:
      - assigned
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Define team names and webhooks
        run: |
          declare -A teams=(
            ["davidsenthil"]="https://jaggaer.webhook.office.com/webhookb2/06a5f793-6e21-4e3c-92d4-5ad2e5a85117@7e4fc837-87aa-4740-859d-1ea52f02e37b/IncomingWebhook/a710b48527074fdd9f6b570a3a980c3f/b292915f-88a8-4fef-a002-b5999e3965e5"
            ["team2"]="https://testteam.com/webhookb2/abck"
            # Add more teams and their webhook URLs as needed
          )
          echo "::set-output name=teams::$(declare -p teams)"
      - name: Send Microsoft Teams Notification
        run: |
          reviewers=$(jq -r '.review.reviewers[].login' "$GITHUB_EVENT_PATH")
          creator="${{ github.event.pull_request.user.login }}"
          pr_title="${{ github.event.pull_request.title }}"
          pr_url="${{ github.event.pull_request.html_url }}"
          declare -n teams_array=teams
          for team_name in "${!teams_array[@]}"; do
            for reviewer in $reviewers; do
              if [[ $reviewer == "$team_name" ]]; then
                curl -H "Content-Type: application/json" -d '{
                  "title": "Pull Request Assigned",
                  "text": "'"${creator}"' has assigned a pull request to '"${team_name}"'",
                  "themeColor": "0076D7",
                  "sections": [
                    {
                      "activityTitle": "'"${pr_title}"'",
                      "activitySubtitle": "Created by: '"${creator}"'",
                      "activityText": "'"${pr_url}"'"
                    }
                  ]
                }' "${teams_array[$team_name]}"
              fi
            done
          done
