name: Notify Team on Pull Request Reviewer Assignment

on:
  pull_request:
    types: [assigned]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Microsoft Teams Notification
        run: |
          webhook_url="https://jaggaer.webhook.office.com/webhookb2/06a5f793-6e21-4e3c-92d4-5ad2e5a85117@7e4fc837-87aa-4740-859d-1ea52f02e37b/IncomingWebhook/a710b48527074fdd9f6b570a3a980c3f/b292915f-88a8-4fef-a002-b5999e3965e5"
           creator="${{ github.event.pull_request.user.login }}"
           pr_title="${{ github.event.pull_request.title }}"
           pr_url="${{ github.event.pull_request.html_url }}"
           repo_name="${{ github.repository }}"
           payload='{
          "type": "message",
          "attachments": [
          {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
            "type": "AdaptiveCard",
            "body": [
              {
                "type": "TextBlock",
                "text": "Creator: '"$creator"'"
                "weight": "Bolder",
                "size": "Medium"
              },
              {
                "type": "TextBlock",
                "text": "Title: '"$pr_title"'",
                "wrap": true
              },
              {
                "type": "TextBlock",
                "text": "Repository: '"$repo_name"'",
                "wrap": true
              }
            ],
          "actions": [
            {
              "type": "Action.OpenUrl",
              "title": "View Pull Request",
              "url": "'"$pr_url"'"
            }
          ]
          }
          }
          ]
          }'
          curl -H "Content-Type: application/json" -d "$payload" "$webhook_url"
